import { ShipType } from '../../../../types';

const t: ShipType = {
  name: 'Eta-2 Actis',
  xws: 'eta2actis',
  size: 'Small',
  dial: [
    '1TW',
    '1YW',
    '2EP',
    '2TW',
    '2BB',
    '2FB',
    '2NB',
    '2YW',
    '2RP',
    '3TW',
    '3BB',
    '3FB',
    '3NB',
    '3YW',
    '4FB',
    '4KR',
    '5FW',
  ],
  faction: 'Galactic Republic',
  stats: [
    { type: 'attack', arc: 'Bullseye Arc', value: 3 },
    { type: 'attack', arc: 'Front Arc', value: 2 },
    { type: 'agility', value: 3 },
    { type: 'hull', value: 3 },
  ],
  actions: [
    { type: 'Focus', difficulty: 'White' },
    { type: 'Evade', difficulty: 'White' },
    { type: 'Lock', difficulty: 'Purple' },
    { type: 'Barrel Roll', difficulty: 'White' },
    { type: 'Boost', difficulty: 'White' },
  ],
  ability: {
    name: 'Intuitive Controls',
    text: 'During the System Phase, you may perform a purple [Barrel Roll] or purple [Boost] action.',
  },
  pilots: [
    {
      xws: 'anakinskywalker-eta2actis',
      ffg: 781,
      name: 'Anakin Skywalker',
      cost: 12,
      loadout: 10,
      limited: 1,
      initiative: 6,
      caption: 'Hero of Coruscant',
      slots: [
        'Talent',
        'Force Power',
        'Astromech',
        'Cannon',
        'Modification',
        'Force Power',
      ],
      standard: true,
      force: { value: 3, recovers: 1, side: ['light', 'dark'] },
      epic: true,
      ability:
        'After you or a friendly Obi-Wan Kenobi ship at range 0-3 executes a maneuver, if there are more enemy ships than other friendly ships at range 0-1 of that ship, you may spend 1 [Force]. If you do, that ship removes 1 red token of your choice.',
      keywords: ['Dark Side', 'Jedi', 'Light Side'],
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/pilots/anakinskywalker-eta2actis.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/anakinskywalker-eta2actis.png',
    },
    {
      xws: 'obiwankenobi-eta2actis',
      ffg: 782,
      name: 'Obi-Wan Kenobi',
      cost: 12,
      loadout: 12,
      limited: 1,
      initiative: 5,
      caption: 'Guardian of Democracy',
      slots: [
        'Talent',
        'Force Power',
        'Astromech',
        'Cannon',
        'Modification',
        'Force Power',
      ],
      force: { value: 3, recovers: 1, side: ['light'] },
      standard: true,
      epic: true,
      ability:
        'After you or a friendly Anakin Skywalker ship at range 0-3 executes a maneuver, if there are more enemy ships than other friendly ships at range 0-1 of that ship, you may spend 1 [Force]. If you do, that ship gains 1 focus token.',
      keywords: ['Jedi', 'Light Side'],
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/pilots/obiwankenobi-eta2actis.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/obiwankenobi-eta2actis.png',
    },
    {
      xws: 'aaylasecura',
      ffg: 783,
      name: 'Aayla Secura',
      cost: 11,
      limited: 1,
      initiative: 5,
      caption: 'Confident Warrior',
      slots: [
        'Talent',
        'Force Power',
        'Astromech',
        'Cannon',
        'Modification',
        'Force Power',
      ],
      force: { value: 2, recovers: 1, side: ['light'] },
      standard: true,
      epic: true,
      ability:
        'While an enemy ship in your [Front Arc] at range 0-1 performs an attack, the defender may change 1 blank result to a [Focus] result.',
      keywords: ['Jedi', 'Light Side'],
      loadout: 11,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/aaylasecura.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/aaylasecura.png',
    },
    {
      name: 'Shaak Ti',
      xws: 'shaakti',
      initiative: 4,
      limited: 1,
      caption: 'Compassionate Mentor',
      standard: true,
      force: { value: 2, recovers: 1, side: ['light'] },
      ability:
        'At the start of the End Phase, you may spend any number of [Force] to choose that many friendly ships at range 0-2. Each chosen ship does not remove 1 focus or evade token during this End Phase.',
      slots: [
        'Talent',
        'Force Power',
        'Astromech',
        'Cannon',
        'Modification',
        'Force Power',
      ],
      cost: 12,
      epic: true,
      ffg: 784,
      keywords: ['Jedi', 'Light Side'],
      loadout: 14,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/shaakti.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/shaakti.png',
    },
    {
      name: 'Jedi General',
      xws: 'jedigeneral',
      initiative: 4,
      limited: 0,
      text: 'As the Clone Wars take their toll on the ranks of the Jedi Order, those that remain must assume even greater responsibilities in the Grand Army of the Republic.',
      standard: true,
      force: { value: 2, recovers: 1, side: ['light'] },
      slots: ['Talent', 'Force Power', 'Astromech', 'Cannon', 'Modification'],
      cost: 10,
      epic: true,
      ffg: 786,
      keywords: ['Jedi', 'Light Side'],
      loadout: 9,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/jedigeneral.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/jedigeneral.png',
      caption: '',
    },
    {
      name: 'Yoda',
      xws: 'yoda',
      initiative: 3,
      limited: 1,
      caption: 'Grand Master',
      standard: true,
      force: { value: 3, recovers: 1, side: ['light'] },
      ability:
        'After another friendly ship at range 0-3 spends 1 or more [Force], you may spend 1 [Force]. If you do, that ship recovers 1 [Force].',
      slots: [
        'Talent',
        'Force Power',
        'Astromech',
        'Cannon',
        'Modification',
        'Force Power',
      ],
      cost: 10,
      epic: true,
      ffg: 785,
      keywords: ['Jedi', 'Light Side'],
      loadout: 8,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/yoda.png',
      artwork: 'https://infinitearenas.com/xw2/images/artwork/pilots/yoda.png',
    },
    {
      xws: 'anakinskywalker-siegeofcoruscant',
      name: 'Anakin Skywalker',
      cost: 12,
      loadout: 0,
      limited: 1,
      initiative: 6,
      caption: 'Siege of Coruscant',
      standard: true,
      force: { value: 3, recovers: 1, side: ['light', 'dark'] },
      epic: true,
      ability:
        'After you or a friendly Obi-Wan Kenobi ship at range 0-3 fully executes a maneuver, if there are more enemy ships than other friendly ships at range 0-1 of that ship, you may spend 1 [Force]. If you do, that ship may perform a [Barrel Roll] action.',
      keywords: ['Dark Side', 'Jedi', 'Light Side'],
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/quickbuilds/anakinskywalker-siegeofcoruscant.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/anakinskywalker-eta2actis.png',
      standardLoadout: [
        'malice',
        'ancillaryionweapons-siegeofcoruscant',
        'r2d2-republic',
      ],
      ffg: 991,
      slots: [],
    },
    {
      xws: 'obiwankenobi-siegeofcoruscant',
      name: 'Obi-Wan Kenobi',
      cost: 11,
      loadout: 0,
      limited: 1,
      initiative: 5,
      caption: 'Siege of Coruscant',
      force: { value: 3, recovers: 1, side: ['light'] },
      standard: true,
      epic: true,
      ability:
        'After you or a friendly Anakin Skywalker at range 0-3 fully executes a maneuver, if there are more enemy ships than other friendly ships at range 0-1 of that ship, you may spend 1 [Force]. If you do, that ship may perform a [Boost] action.',
      keywords: ['Jedi', 'Light Side'],
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/quickbuilds/obiwankenobi-siegeofcoruscant.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/obiwankenobi-eta2actis.png',
      standardLoadout: [
        'patience',
        'ancillaryionweapons-siegeofcoruscant',
        'r4p17-siegeofcoruscant',
      ],
      ffg: 992,
      slots: [],
    },
    {
      name: 'Shaak Ti',
      xws: 'shaakti-siegeofcoruscant',
      initiative: 4,
      limited: 1,
      caption: 'Siege of Coruscant',
      standard: true,
      force: { value: 2, recovers: 1, side: ['light'] },
      ability:
        'At the start of the End Phase, you may perfrom a purple [Coordinate] action, even while stressed. After you perform a [Coordinate] action, if the chosen ship has the Born for This ship ability, you may coordinate 1 additional ship.',
      cost: 10,
      epic: true,
      keywords: ['Jedi', 'Light Side'],
      loadout: 0,
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/quickbuilds/shaakti-siegeofcoruscant.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/shaakti.png',
      standardLoadout: [
        'marksmanship',
        'brilliantevasion',
        'ancillaryionweapons-siegeofcoruscant',
        'r4pastromech',
      ],
      ffg: 993,
      slots: [],
    },
    {
      name: 'Kit Fisto',
      xws: 'kitfisto',
      initiative: 4,
      limited: 1,
      shipAbility: {
        name: 'Intuitive Controls',
        text: 'During the System Phase, you may perform a purple [Barrel Roll] or purple [Boost] action.',
      },
      caption: 'Enthusiastic Exemplar',
      standard: true,
      extended: true,
      force: { value: 2, recovers: 1, side: ['light'] },
      ability:
        "While another friendly ship defends, if the attacker is in its [Bullseye Arc], you may spend 1 [Force] to change 1 of the defender's blank results to a [Focus] result.",
      cost: 10,
      loadout: 8,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/kitfisto.png',
      image: 'https://infinitearenas.com/xw2/images/pilots/kitfisto.png',
      slots: [
        'Talent',
        'Force Power',
        'Astromech',
        'Cannon',
        'Modification',
        'Force Power',
      ],
      keywords: ['Jedi', 'Light Side'],
      epic: true,
      ffg: 994,
    },
  ],
  ffg: 76,
  icon: 'https://infinitearenas.com/xw2/images/shipicons/galactic-republic/I_Eta-2_Actis.png',
};

export default t;
