import { ShipType } from '../../../../types';

const t: ShipType = {
  name: 'TIE/D Defender',
  xws: 'tieddefender',
  ffg: 18,
  size: 'Small',
  dial: [
    '1TR',
    '1BB',
    '1NB',
    '1YR',
    '2TR',
    '2BW',
    '2FB',
    '2NW',
    '2YR',
    '2KR',
    '3TW',
    '3BW',
    '3FB',
    '3NW',
    '3YW',
    '4FB',
    '4KW',
    '5FB',
  ],
  faction: 'Galactic Empire',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { type: 'agility', value: 3 },
    { type: 'hull', value: 3 },
    { type: 'shields', value: 4 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Evade' },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'White', type: 'Barrel Roll' },
    { difficulty: 'White', type: 'Boost' },
  ],
  ability: {
    name: 'Full Throttle',
    text: 'After you fully execute a speed 3-5 maneuver, you may perform an [Evade] action.',
  },
  icon: 'https://infinitearenas.com/xw2/images/shipicons/galactic-empire/I_TIEDefender.png',
  pilots: [
    {
      name: 'Colonel Vessery',
      caption: 'Contemplative Commander',
      initiative: 4,
      limited: 1,
      cost: 17,
      xws: 'colonelvessery',
      ability:
        'While you perform an attack against a locked ship, after you roll attack dice, you may acquire a lock on the defender.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Modification',
        'Sensor',
        'Configuration',
        'Cannon',
      ],
      ffg: 123,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 12,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/colonelvessery.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/colonelvessery.png',
    },
    {
      name: 'Countess Ryad',
      caption: 'Cutthroat Politico',
      initiative: 4,
      limited: 1,
      cost: 16,
      xws: 'countessryad',
      ability:
        'While you would execute a [Straight] maneuver, you may increase the difficulty of the maneuver. If you do, execute it as a [Koiogran Turn] maneuver instead.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Modification',
        'Sensor',
        'Configuration',
        'Modification',
      ],
      ffg: 124,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 9,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/countessryad.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/countessryad.png',
    },
    {
      name: 'Delta Squadron Pilot',
      initiative: 1,
      limited: 0,
      cost: 15,
      xws: 'deltasquadronpilot',
      text: 'In addition to its missile launchers and six wingtip laser cannons, the formidable TIE defender is equipped with deflector shields and a hyperdrive.',
      slots: ['Cannon', 'Missile', 'Modification', 'Sensor', 'Configuration'],
      ffg: 126,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 9,
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/pilots/deltasquadronpilot.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/deltasquadronpilot.png',
      caption: '',
    },
    {
      name: 'Onyx Squadron Ace',
      initiative: 4,
      limited: 0,
      cost: 16,
      xws: 'onyxsquadronace',
      text: 'The experimental TIE defender outclasses all other contemporary starfighters, though its size, speed, and array of weapons come at a tremendous cost in credits.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Modification',
        'Sensor',
        'Configuration',
      ],
      ffg: 125,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 10,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/onyxsquadronace.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/onyxsquadronace.png',
      caption: '',
    },
    {
      name: 'Rexler Brath',
      caption: 'Onyx Leader',
      initiative: 5,
      limited: 1,
      cost: 18,
      xws: 'rexlerbrath',
      ability:
        "After you perform an attack that hits, if you are evading, expose 1 of the defender's damage cards.",
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Modification',
        'Sensor',
        'Configuration',
      ],
      ffg: 122,
      standard: true,
      epic: true,
      keywords: ['TIE'],
      loadout: 13,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/rexlerbrath.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/rexlerbrath.png',
    },
    {
      xws: 'vultskerris',
      name: 'Vult Skerris',
      caption: 'Arrogant Ace',
      cost: 17,
      initiative: 5,
      limited: 1,
      ability:
        'Action: Gain 1 strain token to recover 1 [Charge]. Before you engage, you may spend 1 [Charge] to perform an action.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Modification',
        'Sensor',
        'Configuration',
        'Talent',
      ],
      standard: true,
      epic: true,
      keywords: ['TIE'],
      ffg: 887,
      loadout: 11,
      extended: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/vultskerris.png',
      image: 'https://infinitearenas.com/xw2/images/pilots/vultskerris.png',
    },
    {
      xws: 'darthvader-tieddefender',
      name: 'Darth Vader',
      caption: 'Dark Lord of the Sith',
      cost: 21,
      initiative: 6,
      limited: 1,
      ability:
        'You cannot spend [Force] except while attacking. While you perform an attack, you may spend 1 [Force] to change 1 blank result to a [Hit] result.',
      force: { value: 3, recovers: 1, side: ['dark'] },
      slots: [
        'Cannon',
        'Missile',
        'Modification',
        'Configuration',
        'Force Power',
        'Force Power',
      ],
      standard: true,
      epic: true,
      keywords: ['Dark Side', 'Sith', 'TIE'],
      ffg: 886,
      loadout: 14,
      extended: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/darthvader-tieddefender.png',
      image:
        'https://infinitearenas.com/xw2/images/pilots/darthvader-tieddefender.png',
    },
    {
      xws: 'captaindobbs',
      name: 'Captain Dobbs',
      caption: 'Reliable Replacement',
      cost: 16,
      initiative: 3,
      limited: 1,
      ability:
        'While another friendly ship at range 0-1 defends, before the Neutralize Results step, if you are in the attack arc and are not ionized, you may gain 1 ion token to cancel 1 [Hit] result.',
      slots: [
        'Talent',
        'Cannon',
        'Missile',
        'Modification',
        'Sensor',
        'Configuration',
      ],
      standard: true,
      epic: true,
      keywords: ['TIE'],
      ffg: 888,
      loadout: 10,
      extended: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/captaindobbs.png',
      image: 'https://infinitearenas.com/xw2/images/pilots/captaindobbs.png',
    },
    {
      xws: 'captainyorr-battleoverendor',
      name: 'Captain Yorr',
      caption: 'Battle Over Endor',
      cost: 17,
      initiative: 4,
      limited: 1,
      ability:
        'After you perform a primary attack that hits, you may spend 1 [Charge] to perform a bonus [Cannon] attack.',
      charges: { value: 2, recovers: 0 },
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        {
          difficulty: 'White',
          type: 'Evade',
          linked: { difficulty: 'Red', type: 'Barrel Roll' },
        },
        { difficulty: 'White', type: 'Lock' },
        { difficulty: 'White', type: 'Barrel Roll' },
        { difficulty: 'White', type: 'Boost' },
      ],
      shipAbility: {
        name: 'Chiss Engineering',
        text: 'After you fully execute a speed 3-5 maneuver, you may perform a [Lock] action. While attacking, if you are not stressed, you may spend 1 [Shield] to apply the range 1 bonus.',
      },
      standardLoadout: [
        'noescape-battleoverendor',
        'predator',
        'ioncannon',
        'computerassistedhandling-battleoverendor',
      ],
      standard: true,
      epic: true,
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/quickbuilds/captainyorr-battleoverendor.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/captainyorr-battleoverendor.png',
      loadout: 0,
      ffg: 937,
      slots: [],
    },
    {
      xws: 'coloneljendon-battleoverendor',
      name: 'Colonel Jendon',
      caption: 'Battle Over Endor',
      cost: 20,
      initiative: 6,
      limited: 1,
      ability:
        'While you defend, if you are not shielded, you may change 1 of your blank results to a [Focus] result.',
      charges: { value: 2, recovers: 0 },
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        {
          difficulty: 'White',
          type: 'Evade',
          linked: { difficulty: 'Red', type: 'Barrel Roll' },
        },
        { difficulty: 'White', type: 'Lock' },
        { difficulty: 'White', type: 'Barrel Roll' },
        { difficulty: 'White', type: 'Boost' },
      ],
      shipAbility: {
        name: 'Chiss Engineering',
        text: 'After you fully execute a speed 3-5 maneuver, you may perform a [Lock] action. While attacking, if you are not stressed, you may spend 1 [Shield] to apply the range 1 bonus.',
      },
      standardLoadout: [
        'noescape-battleoverendor',
        'pushthelimit-battleoverendor',
        'protoncannons',
        'computerassistedhandling-battleoverendor',
      ],
      standard: true,
      epic: true,
      extended: true,
      image:
        'https://infinitearenas.com/xw2/images/quickbuilds/coloneljendon-battleoverendor.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/coloneljendon-battleoverendor.png',
      loadout: 0,
      ffg: 938,
      slots: [],
    },
  ],
};

export default t;
