import { ShipType } from '../../../../types';

const t: ShipType = {
  name: 'TIE/ln Fighter',
  xws: 'tielnfighter',
  size: 'Small',
  dial: [
    '1TW',
    '1YW',
    '2TW',
    '2BB',
    '2FB',
    '2NB',
    '2YW',
    '3TW',
    '3BW',
    '3FB',
    '3NW',
    '3YW',
    '3KR',
    '4FW',
    '4KR',
    '5FW',
  ],
  dialCodes: ['TF'],
  faction: 'Galactic Empire',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 2 },
    { type: 'agility', value: 3 },
    { type: 'hull', value: 3 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Evade' },
    { difficulty: 'White', type: 'Barrel Roll' },
  ],
  icon: 'https://infinitearenas.com/xw2/images/shipicons/galactic-empire/I_TIEFighter.png',
  pilots: [
    {
      name: '“Howlrunner”',
      caption: 'Obsidian Leader',
      initiative: 5,
      limited: 1,
      cost: 39,
      xws: 'howlrunner',
      ability:
        'While a friendly ship at range 0-1 performs a primary attack, that ship may reroll 1 attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/howlrunner.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/howlrunner.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 81,
      extended: true,
    },
    {
      name: '“Mauler” Mithel',
      caption: 'Black Two',
      initiative: 5,
      limited: 1,
      cost: 29,
      xws: 'maulermithel',
      ability:
        'While you perform an attack at attack range 1, roll 1 additional attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/maulermithel.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/maulermithel.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 80,
      extended: true,
    },
    {
      name: '“Night Beast”',
      caption: 'Obsidian Two',
      initiative: 2,
      limited: 1,
      cost: 22,
      xws: 'nightbeast',
      ability:
        'After you fully execute a blue maneuver, you may perform a [Focus] action.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/nightbeast.png',
      slots: ['Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/nightbeast.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 88,
      extended: true,
    },
    {
      name: '“Scourge” Skutu',
      caption: 'Seasoned Veteran',
      initiative: 5,
      limited: 1,
      cost: 28,
      xws: 'scourgeskutu',
      ability:
        'While you perform an attack against a defender in your [Bullseye Arc], roll 1 additional attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/scourgeskutu.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/scourgeskutu.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 82,
      extended: true,
    },
    {
      name: '“Wampa”',
      caption: 'Black Eleven',
      initiative: 1,
      limited: 1,
      cost: 27,
      xws: 'wampa',
      ability:
        'While you perform an attack, you may spend 1 [Charge] to roll 1 additional attack die. After defending, lose 1 [Charge].',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/wampa.png',
      charges: { value: 1, recovers: 1 },
      slots: ['Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/wampa.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 89,
      extended: true,
    },
    {
      name: 'Academy Pilot',
      initiative: 1,
      limited: 0,
      cost: 22,
      xws: 'academypilot',
      text: 'The Galactic Empire uses the fast and agile TIE/ln, developed by Sienar Fleet Systems and produced in staggering quantity, as its primary starfighter.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/academypilot.png',
      slots: ['Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/academypilot.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 92,
      extended: true,
    },
    {
      name: 'Black Squadron Ace',
      initiative: 3,
      limited: 0,
      cost: 24,
      xws: 'blacksquadronace',
      text: 'The elite TIE/ln pilots of Black Squadron accompanied Darth Vader on a devastating strike against the Rebel forces at the Battle of Yavin.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/blacksquadronace.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/blacksquadronace.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 90,
      extended: true,
    },
    {
      name: 'Del Meeko',
      caption: 'Inferno Three',
      initiative: 4,
      limited: 1,
      cost: 27,
      xws: 'delmeeko',
      ability:
        'While a friendly ship at range 0-2 defends against a damaged attacker, the defender may reroll 1 defense die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/delmeeko.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/delmeeko.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 85,
      extended: true,
    },
    {
      name: 'Gideon Hask',
      caption: 'Inferno Two',
      initiative: 4,
      limited: 1,
      cost: 27,
      xws: 'gideonhask',
      ability:
        'While you perform an attack against a damaged defender, roll 1 additional attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/gideonhask.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/gideonhask.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 84,
      extended: true,
    },
    {
      name: 'Iden Versio',
      caption: 'Inferno Leader',
      initiative: 4,
      limited: 1,
      cost: 42,
      xws: 'idenversio',
      ability:
        'Before a friendly TIE/ln fighter at range 0-1 would suffer 1 or more damage, you may spend 1 [Charge]. If you do, prevent that damage.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/idenversio.png',
      charges: { value: 1, recovers: 0 },
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/idenversio.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 83,
      extended: true,
    },
    {
      name: 'Obsidian Squadron Pilot',
      initiative: 2,
      limited: 0,
      cost: 23,
      xws: 'obsidiansquadronpilot',
      text: "The TIE fighter's Twin Ion Engine system was designed for speed, making the TIE/ln one of the most maneuverable starships ever mass-produced.",
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/obsidiansquadronpilot.png',
      slots: ['Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/obsidiansquadronpilot.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 91,
      extended: true,
    },
    {
      name: 'Seyn Marana',
      caption: 'Inferno Four',
      initiative: 4,
      limited: 1,
      cost: 27,
      xws: 'seynmarana',
      ability:
        'While you perform an attack, you may spend 1 [Critical Hit] result. If you do, deal 1 facedown damage card to the defender, then cancel your remaining results.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/seynmarana.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/seynmarana.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 86,
      extended: true,
    },
    {
      name: 'Valen Rudor',
      caption: 'Braggadocious Baron',
      initiative: 3,
      limited: 1,
      cost: 23,
      xws: 'valenrudor',
      ability:
        'After a friendly ship at range 0-1 defends (after damage is resolved, if any), you may perform an action.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/valenrudor.png',
      slots: ['Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/valenrudor.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 87,
      extended: true,
    },
    {
      name: 'ISB Jingoist',
      caption: 'Heartless Enforcer',
      initiative: 4,
      limited: 2,
      cost: 28,
      xws: 'isbjingoist',
      ability:
        'Before you engage, you may choose 1 enemy ship in your [Front Arc] at range 0-1. If you do, that ship gains 1 deplete or strain token of your choice unless it chooses to remove 1 green token.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/isbjingoist.png',
      slots: ['Talent', 'Illicit', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/isbjingoist.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 948,
      extended: true,
    },
    {
      name: 'Moff Gideon',
      caption: 'Ruthless Remnant Leader',
      initiative: 4,
      limited: 1,
      cost: 31,
      xws: 'moffgideon',
      charges: { value: 2, recovers: 1 },
      ability:
        'While an enemy ship at range 1-3 defends, before attack dice are rolled, you may spend 1 [Charge] and choose a friendly ship at range 0-1 of the defender. If you do, defense dice cannot be modified during this attack and the chosen friendly ship gains 1 strain token.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/moffgideon.png',
      slots: ['Talent', 'Talent', 'Modification'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/moffgideon.png',
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 949,
      extended: true,
    },
    {
      name: '“Backstabber”',
      caption: 'Battle of Yavin',
      initiative: 5,
      limited: 1,
      cost: 38,
      xws: 'backstabber-battleofyavin',
      ability:
        'While you perform a primary attack, if a friendly Darth Vader or “Mauler” Mithel is in your [Left Arc] or [Right Arc] at range 0-1, roll 1 additional attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/backstabber-battleofyavin.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/backstabber-battleofyavin.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      standardLoadout: ['crackshot', 'disciplined', 'afterburners'],
      standard: false,
      keywords: ['TIE'],
      epic: true,
      ffg: 950,
      extended: true,
    },
    {
      name: '“Backstabber”',
      caption: 'Battle of Yavin',
      initiative: 5,
      limited: 1,
      cost: 36,
      xws: 'backstabber-battleofyavin-lsl',
      ability:
        'While you perform a primary attack, if a friendly Darth Vader or “Mauler” Mithel is in your [Left Arc] or [Right Arc] at range 0-1, roll 1 additional attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/backstabber-battleofyavin-lsl.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/backstabber-battleofyavin-lsl.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      slots: ['Talent'],
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 1187,
      extended: true,
    },
    {
      name: '“Dark Curse”',
      caption: 'Battle of Yavin',
      initiative: 6,
      limited: 1,
      cost: 37,
      xws: 'darkcurse-battleofyavin',
      ability: "While you defend, the attacker's dice cannot be modified.",
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/darkcurse-battleofyavin.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/darkcurse-battleofyavin.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      standardLoadout: ['ruthless', 'precisionionengines'],
      standard: false,
      keywords: ['TIE'],
      epic: true,
      ffg: 951,
      extended: true,
    },
    {
      name: '“Dark Curse”',
      caption: 'Battle of Yavin',
      initiative: 6,
      limited: 1,
      cost: 34,
      xws: 'darkcurse-battleofyavin-lsl',
      ability: "While you defend, the attacker's dice cannot be modified.",
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/darkcurse-battleofyavin-lsl.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/darkcurse-battleofyavin-lsl.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      slots: ['Talent'],
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 1188,
      extended: true,
    },
    {
      name: '“Mauler” Mithel',
      caption: 'Battle of Yavin',
      initiative: 5,
      limited: 1,
      cost: 37,
      xws: 'maulermithel-battleofyavin',
      ability:
        'While you perform a primary attack, if a friendly Darth Vader or “Backstabber” is in your [Left Arc] or [Right Arc] at range 0-1, roll 1 additional attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/maulermithel-battleofyavin.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/maulermithel-battleofyavin.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      standardLoadout: ['predator', 'afterburners'],
      standard: false,
      keywords: ['TIE'],
      epic: true,
      ffg: 952,
      extended: true,
    },
    {
      name: '“Mauler” Mithel',
      caption: 'Battle of Yavin',
      initiative: 5,
      limited: 1,
      cost: 36,
      xws: 'maulermithel-battleofyavin-lsl',
      ability:
        'While you perform a primary attack, if a friendly Darth Vader or “Backstabber” is in your [Left Arc] or [Right Arc] at range 0-1, roll 1 additional attack die.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/maulermithel-battleofyavin-lsl.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/maulermithel-battleofyavin-lsl.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      slots: ['Talent'],
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 1189,
      extended: true,
    },
    {
      name: '“Wampa”',
      caption: 'Battle of Yavin',
      initiative: 1,
      limited: 1,
      cost: 39,
      xws: 'wampa-battleofyavin',
      ability:
        'While you perform an attack, you may spend 1 [Charge] to roll 1 additional attack die. After defending, lose 1 [Charge].',
      charges: { value: 1, recovers: 1 },
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/wampa-battleofyavin.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/wampa-battleofyavin.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      standardLoadout: ['elusive', 'vengeful-battleofyavin'],
      standard: false,
      keywords: ['TIE'],
      epic: true,
      ffg: 953,
      extended: true,
    },
    {
      name: '“Wampa”',
      caption: 'Battle of Yavin',
      initiative: 1,
      limited: 1,
      cost: 31,
      xws: 'wampa-battleofyavin-lsl',
      ability:
        'While you perform an attack, you may spend 1 [Charge] to roll 1 additional attack die. After defending, lose 1 [Charge].',
      charges: { value: 1, recovers: 1 },
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/wampa-battleofyavin-lsl.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/wampa-battleofyavin-lsl.png',
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      slots: [],
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 1190,
      extended: true,
    },
    {
      name: 'Magna Tolvan',
      caption: 'Cold Tyrant',
      initiative: 3,
      limited: 1,
      cost: 24,
      xws: 'magnatolvan',
      ability:
        'While you have 2 or fewer stress tokens, you can perform white actions, even while stressed. After you gain a stress token, you may perform a white action, if able.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/magnatolvan.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/magnatolvan.png',
      slots: ['Talent', 'Modification'],
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 954,
      extended: true,
    },
    {
      name: 'Yrica Quell',
      caption: 'Consumed by Duty',
      initiative: 3,
      limited: 1,
      cost: 24,
      xws: 'yricaquell',
      ability:
        'After you fully execute a maneuver, you may acquire a lock on an enemy ship in your [Bullseye Arc].',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/yricaquell.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/yricaquell.png',
      slots: ['Talent', 'Modification'],
      standard: true,
      keywords: ['TIE'],
      epic: true,
      ffg: 955,
      extended: true,
    },
    {
      name: 'Iden Versio',
      caption: 'Inferno Leader',
      initiative: 4,
      limited: 1,
      cost: 45,
      standardLoadout: ['disciplined', 'elusive'],
      xws: 'idenversio-swz105',
      ability:
        'Before a friendly TIE/ln fighter at range 0-1 would suffer 1 or more damage, you may spend 1 [Charge]. If you do, prevent that damage.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/idenversio-swz105.png',
      charges: { value: 1, recovers: 0 },
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/idenversio-swz105.png',
      standard: false,
      keywords: ['TIE'],
      epic: true,
      ffg: 956,
      extended: true,
    },
    {
      name: '“Night Beast”',
      caption: 'Obsidian Two',
      initiative: 2,
      limited: 1,
      cost: 26,
      xws: 'nightbeast-swz105',
      ability:
        'After you fully execute a blue maneuver, you may perform a [Focus] action.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/nightbeast-swz105.png',
      standardLoadout: ['disciplined', 'predator'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/nightbeast-swz105.png',
      standard: false,
      keywords: ['TIE'],
      epic: true,
      ffg: 957,
      extended: true,
    },
    {
      name: 'Valen Rudor',
      caption: 'Braggadocious Baron',
      initiative: 3,
      limited: 1,
      cost: 27,
      xws: 'valenrudor-swz105',
      ability:
        'After a friendly ship at range 0-1 defends (after damage is resolved, if any), you may perform an action.',
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/valenrudor-swz105.png',
      standardLoadout: ['disciplined', 'precisionionengines'],
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/valenrudor-swz105.png',
      standard: false,
      keywords: ['TIE'],
      epic: true,
      ffg: 958,
      extended: true,
    },
    {
      name: 'Lieutenant Hebsly',
      caption: 'Battle Over Endor',
      xws: 'lieutenanthebsly-battleoverendor',
      initiative: 3,
      limited: 1,
      shipAbility: {
        name: 'Formed Up',
        text: 'At the end of the End Phase, if there is another friendly TIE/ln Fighter at range 0-1, you may remove 1 stress token.',
      },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        { difficulty: 'White', type: 'Evade' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Evade' },
        },
        { difficulty: 'Red', type: 'Boost' },
      ],
      cost: 51,
      standardLoadout: [
        'collected-battleoverendor',
        'elusive',
        'noescape-battleoverendor',
      ],
      ability:
        'After you defend, you may perform a red [Boost] action, even while stressed.',
      keywords: ['TIE'],
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/lieutenanthebsly-battleoverendor.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/lieutenanthebsly-battleoverendor.png',
      standard: false,
      epic: true,
      ffg: 959,
      extended: true,
    },
    {
      name: 'Lieutenant Hebsly',
      caption: 'Battle Over Endor',
      xws: 'lieutenanthebsly-battleoverendor-lsl',
      initiative: 3,
      limited: 1,
      shipAbility: {
        name: 'Formed Up',
        text: 'At the end of the End Phase, if there is another friendly TIE/ln Fighter at range 0-1, you may remove 1 stress token.',
      },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        { difficulty: 'White', type: 'Evade' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Evade' },
        },
        { difficulty: 'Red', type: 'Boost' },
      ],
      cost: 38,
      slots: ['Talent'],
      ability:
        'After you defend, you may perform a red [Boost] action, even while stressed.',
      keywords: ['TIE'],
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/lieutenanthebsly-battleoverendor-lsl.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/lieutenanthebsly-battleoverendor-lsl.png',
      standard: true,
      epic: true,
      ffg: 1191,
      extended: true,
    },
    {
      name: 'Scythe 6',
      caption: 'Battle Over Endor',
      xws: 'scythe6-battleoverendor',
      initiative: 2,
      limited: 1,
      shipAbility: {
        name: 'Formed Up',
        text: 'At the end of the End Phase, if there is another friendly TIE/ln Fighter at range 0-1, you may remove 1 stress token.',
      },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        { difficulty: 'White', type: 'Evade' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Evade' },
        },
      ],
      cost: 53,
      standardLoadout: [
        'noescape-battleoverendor',
        'predator',
        'ionmaneuveringjet-battleoverendor',
        'targetingmatrix-battleoverendor',
      ],
      ability:
        'While you perform an attack at attack range 1-2, roll 1 additional attack die.',
      keywords: ['TIE'],
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/scythe6-battleoverendor.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/scythe6-battleoverendor.png',
      standard: false,
      epic: true,
      ffg: 960,
      extended: true,
    },
    {
      name: 'Scythe 6',
      caption: 'Battle Over Endor',
      xws: 'scythe6-battleoverendor-lsl',
      initiative: 2,
      limited: 1,
      shipAbility: {
        name: 'Formed Up',
        text: 'At the end of the End Phase, if there is another friendly TIE/ln Fighter at range 0-1, you may remove 1 stress token.',
      },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 4 },
      ],
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        { difficulty: 'White', type: 'Evade' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Evade' },
        },
      ],
      cost: 42,
      slots: [],
      ability:
        'While you perform an attack at attack range 1-2, roll 1 additional attack die.',
      keywords: ['TIE'],
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/scythe6-battleoverendor-lsl.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/scythe6-battleoverendor-lsl.png',
      standard: true,
      epic: true,
      ffg: 1192,
      extended: true,
    },
    {
      name: 'Major Mianda',
      caption: 'Battle Over Endor',
      xws: 'majormianda-battleoverendor',
      initiative: 5,
      limited: 1,
      shipAbility: {
        name: 'Formed Up',
        text: 'At the end of the End Phase, if there is another friendly TIE/ln Fighter at range 0-1, you may remove 1 stress token.',
      },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 3 },
        { type: 'shields', value: 1 },
      ],
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        { difficulty: 'White', type: 'Evade' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Evade' },
        },
        { difficulty: 'Red', type: 'Coordinate' },
      ],
      cost: 48,
      standardLoadout: ['noescape-battleoverendor', 'ruthless', 'swarmtactics'],
      ability:
        'During the End Phase, you may choose up to 2 friendly small ships at range 0-2. You and the chosen ships may perform a red [Barrel Roll] or red [Boost] action.',
      keywords: ['TIE'],
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/majormianda-battleoverendor.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/majormianda-battleoverendor.png',
      standard: false,
      epic: true,
      ffg: 961,
      extended: true,
    },
    {
      name: 'Major Mianda',
      caption: 'Battle Over Endor',
      xws: 'majormianda-battleoverendor-lsl',
      initiative: 5,
      limited: 1,
      shipAbility: {
        name: 'Formed Up',
        text: 'At the end of the End Phase, if there is another friendly TIE/ln Fighter at range 0-1, you may remove 1 stress token.',
      },
      stats: [
        { arc: 'Front Arc', type: 'attack', value: 2 },
        { type: 'agility', value: 3 },
        { type: 'hull', value: 3 },
        { type: 'shields', value: 1 },
      ],
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        { difficulty: 'White', type: 'Evade' },
        {
          difficulty: 'White',
          type: 'Barrel Roll',
          linked: { difficulty: 'Red', type: 'Evade' },
        },
        { difficulty: 'Red', type: 'Coordinate' },
      ],
      cost: 41,
      slots: ['Talent'],
      ability:
        'During the End Phase, you may choose up to 2 friendly small ships at range 0-2. You and the chosen ships may perform a red [Barrel Roll] or red [Boost] action.',
      keywords: ['TIE'],
      image:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/En/pilots/majormianda-battleoverendor-lsl.png',
      artwork:
        'https://raw.githubusercontent.com/SogeMoge/x-wing2.0-project-goldenrod/2.0-legacy/src/images/Art/pilots/majormianda-battleoverendor-lsl.png',
      standard: true,
      epic: true,
      ffg: 1193,
      extended: true,
    },
  ],
};

export default t;
