import { ShipType } from '../../../../types';

const t: ShipType = {
  name: 'Firespray-class Patrol Craft',
  xws: 'firesprayclasspatrolcraft',
  ffg: 10,
  size: 'Medium',
  dial: [
    '1TW',
    '1BB',
    '1FB',
    '1NB',
    '1YW',
    '2TW',
    '2BW',
    '2FB',
    '2NW',
    '2YW',
    '3ER',
    '3BW',
    '3FB',
    '3NW',
    '3RR',
    '4FW',
    '4KR',
  ],
  faction: 'Scum and Villainy',
  stats: [
    { arc: 'Front Arc', type: 'attack', value: 3 },
    { arc: 'Rear Arc', type: 'attack', value: 3 },
    { type: 'agility', value: 2 },
    { type: 'hull', value: 6 },
    { type: 'shields', value: 4 },
  ],
  actions: [
    { difficulty: 'White', type: 'Focus' },
    { difficulty: 'White', type: 'Lock' },
    { difficulty: 'Red', type: 'Reinforce' },
    { difficulty: 'White', type: 'Boost' },
  ],
  icon: 'https://infinitearenas.com/xw2/images/shipicons/scum-and-villainy/I_FIrespray.png',
  pilots: [
    {
      name: 'Boba Fett',
      caption: 'Notorious Bounty Hunter',
      initiative: 5,
      limited: 1,
      cost: 20,
      xws: 'bobafett',
      ability:
        'While you defend or perform an attack, you may reroll 1 of your dice for each enemy ship at range 0-1.',
      slots: [
        'Cannon',
        'Crew',
        'Illicit',
        'Missile',
        'Modification',
        'Device',
        'Title',
        'Talent',
        'Modification',
      ],
      ffg: 149,
      standard: true,
      epic: true,
      keywords: ['Bounty Hunter'],
      loadout: 20,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/bobafett.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/bobafett.png',
    },
    {
      name: 'Bounty Hunter',
      initiative: 2,
      limited: 0,
      cost: 14,
      xws: 'bountyhunter',
      text: 'The Firespray-class patrol craft is infamous for its association with the deadly bounty hunters Jango Fett and Boba Fett, who packed their craft with countless deadly armaments.',
      slots: ['Cannon', 'Crew', 'Illicit', 'Missile', 'Modification', 'Device'],
      ffg: 154,
      standard: true,
      epic: true,
      loadout: 6,
      extended: true,
      keywords: ['Bounty Hunter'],
      image: 'https://infinitearenas.com/xw2/images/pilots/bountyhunter.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/bountyhunter.png',
      caption: '',
    },
    {
      name: 'Emon Azzameen',
      caption: 'Shipping Magnate',
      initiative: 4,
      limited: 1,
      cost: 18,
      xws: 'emonazzameen',
      ability:
        'If you would drop a device using a (1 [Straight]) template, you may use the (3 [Turn Left]), (3 [Straight]), or (3 [Turn Right]) template instead.',
      slots: [
        'Cannon',
        'Crew',
        'Illicit',
        'Missile',
        'Modification',
        'Device',
        'Title',
        'Talent',
      ],
      ffg: 150,
      standard: true,
      epic: true,
      loadout: 20,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/emonazzameen.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/emonazzameen.png',
    },
    {
      name: 'Kath Scarlet',
      caption: 'Captain of the Binayre Pirates',
      initiative: 4,
      limited: 1,
      cost: 15,
      xws: 'kathscarlet',
      ability:
        'While you perform a primary attack, if there is at least 1 friendly non-limited ship at range 0 of the defender, roll 1 additional attack die.',
      slots: [
        'Cannon',
        'Crew',
        'Illicit',
        'Missile',
        'Modification',
        'Device',
        'Title',
        'Talent',
      ],
      ffg: 151,
      standard: true,
      epic: true,
      loadout: 8,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/kathscarlet.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/kathscarlet.png',
    },
    {
      name: 'Koshka Frost',
      caption: 'Icy Professional',
      initiative: 3,
      limited: 1,
      cost: 16,
      xws: 'koshkafrost',
      ability:
        'While you defend or perform an attack, if the enemy ship is stressed, you may reroll 1 of your dice.',
      slots: [
        'Cannon',
        'Crew',
        'Illicit',
        'Missile',
        'Modification',
        'Device',
        'Talent',
      ],
      ffg: 152,
      standard: true,
      epic: true,
      loadout: 13,
      extended: true,
      keywords: ['Bounty Hunter'],
      image: 'https://infinitearenas.com/xw2/images/pilots/koshkafrost.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/koshkafrost.png',
    },
    {
      name: 'Krassis Trelix',
      caption: 'Imperial Deserter',
      initiative: 3,
      limited: 1,
      cost: 17,
      xws: 'krassistrelix',
      ability:
        'You can perform [Front Arc] special attacks from your [Rear Arc]. While you perform a special attack, you may reroll 1 attack die.',
      slots: [
        'Cannon',
        'Crew',
        'Illicit',
        'Missile',
        'Modification',
        'Device',
        'Talent',
      ],
      ffg: 153,
      standard: true,
      epic: true,
      loadout: 18,
      extended: true,
      image: 'https://infinitearenas.com/xw2/images/pilots/krassistrelix.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/krassistrelix.png',
    },
    {
      name: 'Hondo Ohnaka',
      caption: 'I Smell Profit!',
      initiative: 1,
      limited: 1,
      cost: 17,
      loadout: 12,
      xws: 'hondoohnaka',
      ability:
        'Action: Choose 2 non-huge ships at range 0-3 of you that are not friendly to each other. Each chosen ship may perform an action that is on your action bar, even while stressed, in the order of your choice. Then, gain 1 calculate token.',
      image: 'https://infinitearenas.com/xw2/images/pilots/hondoohnaka.png',
      slots: [
        'Cannon',
        'Crew',
        'Illicit',
        'Missile',
        'Modification',
        'Device',
        'Title',
      ],
      standard: true,
      extended: true,
      epic: true,
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/hondoohnaka.png',
      ffg: 1058,
    },
    {
      name: 'Boba Fett',
      caption: 'Armed and Dangerous',
      initiative: 5,
      limited: 1,
      cost: 18,
      loadout: 0,
      xws: 'bobafett-armedanddangerous',
      ability:
        'After another friendly ship defends, if you have a lock on the attacker, you may perform a bonus attack against the attacker.',
      image:
        'https://infinitearenas.com/xw2xwa/images/quickbuilds/bobafett-armedanddangerous.png',
      artwork:
        'https://infinitearenas.com/xw2/images/artwork/pilots/bobafett-armedanddangerous.png',
      standard: true,
      extended: true,
      keywords: ['Bounty Hunter'],
      standardLoadout: [
        'homeingbeacon-armedanddangerous',
        'fennecshand-armedanddangerous',
        'seismiccharges',
        'slavei-swz82',
      ],
      shipActions: [
        { difficulty: 'White', type: 'Focus' },
        { difficulty: 'White', type: 'Lock' },
        {
          difficulty: 'White',
          type: 'Boost',
          linked: { difficulty: 'Red', type: 'Lock' },
        },
      ],
      epic: true,
      ffg: 1110,
      slots: [],
    },
  ],
};

export default t;
